plugins { id 'com.android.application' }

android {
    namespace 'com.medipharm.clinicalsuite'
    compileSdk 35
    defaultConfig {
        applicationId 'com.medipharm.clinicalsuite'
        minSdk 31
        targetSdk 35
        versionCode 3
        versionName '1.0.2'
    }
    buildFeatures { buildConfig true }
    buildTypes { release { minifyEnabled false; shrinkResources false } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
